### PR TITLE
Testing QueryContributors

### PR DESCRIPTION
**Pull request by DIDHAV**

### CODE REVIEW

**Comment by cpetzold** [comment]
Closing this PR but I'll keep the `testing` branch alive.

**Comment by JohnAllen** [comment]
This should be merged right?

**Comment by cpetzold** [comment]
Yeah I guess maybe we jumped the gun on merging the decentralized git stuff then? I'm not sure how we should have the decentralized git and github stuff side by side.

**Comment by JohnAllen** [comment]
Not sure either.  I was actually going to merge everything today but then the two are fundamentally different.  Will be a pain to manage both. I realized that Oraclize queries also cost gas (though they are not super time sensitive so those charges can be low).  

I may not do the Github approach right now, so let's move on and see how much progress we can make on fully decentralizing in 1-2 weeks? Closing...

**Pull request closed without merging**
